### ISSUE TITLE
getting error while activating plugin

### ISSUE THREAD

**Issue by farhanhan173** [DPO-Group/DPO_Gravity_Forms#10]
Hi, 
I am getting error while activating plugin
![Screenshot_1](https://user-images.githubusercontent.com/76624972/215519412-4cc81077-d447-4b27-bdb5-ca3a59bc9815.png)
Please have a look
Thank you

**Comment by bruce-atkinson** [comment]
@farhanhan173 please ensure your server is running PHP 8.0

**Comment by farhanhan173** [comment]
Hello there,
I am running PHP 8.1...
The above error has been resolved but now i am having an issue when i submit the registration form to process payment. I am getting a blank screen with nothing done (no user created).
![image](https://user-images.githubusercontent.com/76624972/216633691-cb72a98c-117e-4b05-b187-e13c73c4cf56.png)
