### ISSUE TITLE
Blank page when submit the gravity form

### ISSUE THREAD

**Issue by farhanhan173** [DPO-Group/DPO_Gravity_Forms#11]
Hello there,
I am running PHP 8.1...
The above error has been resolved but now I am having an issue when I submit the registration form to process payment. I am getting a blank screen with nothing done (no user created).
![216633691-cb72a98c-117e-4b05-b187-e13c73c4cf56](https://user-images.githubusercontent.com/76624972/216774419-1991c60e-6c03-49fc-8847-106c80a20806.png)

**Comment by farhanhan173** [comment]
Could you please response?

**Comment by bruce-atkinson** [comment]
Hi @farhanhan173,

Version 1.0.6 #12 should output the reason for the error.

Please contact the [DPO Pay support team](https://dpogroup.com/contact-us/) should you require any additional assistance.
