### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by IVEN2022** [DPO-Group/DPO_Gravity_Forms#7]
Parse error: syntax error, unexpected '|', expecting '{' in /plugins/gravity-forms-dpo-group-plugin/dpo-group.php on line 179

**Comment by bruce-atkinson** [comment]
@IVEN2022 this report has been booked directly on the support system.

**Comment by IVEN2022** [comment]
The Bug is when I activate the plugin !!!

**Comment by bruce-atkinson** [comment]
According to the ticket thread, you haven't installed Gravity Forms. We will continue all communications on the support ticket.

**Comment by IVEN2022** [comment]
yes the bug not fixed yet
